

# Site
title: Pinal Bhatt's Blog
subtitle: Learning endeavour forever...
description: PBDesk.com | Pinal Bhatt's Blog - Learning endeavour forever... from the desk of Pinal Bhatt
author: Pinal Bhatt
language: en
timezone: America/New_York

# URL
url: http://pbdesk.com
root: /
permalink: :category/:title/
permalink_defaults:



# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: General
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MMM-YYYY
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: material
themeSkin: orange-600

category_generator:
  per_page: 10

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: s3
  bucket: pbdesk.com

feed:
  type: atom
  path: feed.xml
  limit: 20

jsonFeed:
  limit: 25

sitemap:
    path: sitemap.xml

hfc_css:
  enable: true
hfc_html:
  enable: true
hfc_useref:
  enable: false
hfc_js:
  enable: false
  mangle: true
  output:
  compress: true
  exclude:
    - '*.min.js'
hfc_img:
  enable: false
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false
  webp: true
  webpQuality: 75
  gifslice: true
  jpegtran: true
  jpegrecompress: false
  jpegrecompressQuality: 'medium'
  optipng: true
  svgo: true
hfc_favicons:
  enable: false
  src: /assets/images/PBDesk.png
  target: /assets/images/
  icons:
    android: true
    appleIcon: true
    appleStartup: true
    favicons: true

stagings:
  prod:
    url: http://pbdesk.com
  dev:
    url: http://dev.pbdesk.com:4200

