# Logo
logo_image_source: /assets/images/PBDesk2017Logo.png
favicon: /assets/images/PBDeskFavicon.png

# Index Page
index_banner_text: Pinal Bhatt's Blog
index_banner_text_secondary: Learning Endeavour forerver....
index_font_awesome_icon_css: fa fa-magic

# Header
menu:
  Home: /
  Posts: /archives
  Categories: /categories
  Tags: /tags
  About: /about


# Post
default_post_title: Untitled
default_post_icon: fa-file-text-o
default_post_image: /assets/images/default_post.png

# Archive Date Format
archive_date_format: MMM-YYYY
archive_font_awesome_icon_css: fa-folder-open

# About Widget
about_widget_avatar_url: /assets/images/PBDesk.png
about_widget_text: "<i><b>Learning Endeavour forerver...</b></i> <br/>I am Software Engineer and this is my blog.<br> hit me <a target='_blank' href='https://twitter.com/pbdesk'> @PBDesk <i class='fa fa-twitter'></i></a>."


# Comments.
comments:
  # Disqus comments
  disqus_shortname: pbdesk-com

# Google Analytics Tracking ID
google_analytics: UA-9753249-7

twitter_handle: PBDesk
# Social Media Platforms
social_platforms:
  - url: https://www.twitter.com/PBDesk
    icon: twitter
  - url: https://www.facebook.com/Go.PBDesk/
    icon: facebook
  - url: https://www.linkedin.com/in/pinalbhatt
    icon: linkedin
  - url: https://github.com/pinalbhatt/
    icon: github
  - url: /feed.xml
    icon: rss

# Footer about
footer_about: "Learning endeavor forever… from the desk of Pinal Bhatt <br/><br/> <a href='http://www.pbdesk.com'>PBDesk.com - Pinal Bhatt&quot;s Blog</a> © 2017. All Rights Reserved"
