# Logo
logo_image_source: /assets/images/PBDesk2017Logo.png
favicon: /assets/images/PBDeskFavicon.png

# Index Page
index_banner_text: Pinal Bhatt's Blog
index_banner_text_secondary: Learning Endeavour forerver....
index_font_awesome_icon_css: fa fa-magic

# Header
menu:
  Posts: /archives
  Categories: /categories
  Tags: /tags


# Post
default_post_title: Untitled
default_post_icon: fa-file-text-o

# Archive Date Format
archive_date_format: MMM-YYYY
archive_font_awesome_icon_css: fa-folder-open

# About Widget
about_widget_avatar_url: /assets/images/PBDesk.png
about_widget_text: "<i><b>Learning Endeavour forerver...</b></i> <br/>I am Software Engineer and this is my blog.<br> hit me <a target='_blank' href='https://twitter.com/pbdesk'> @PBDesk <i class='fa fa-twitter'></i></a>."


# Comments.
comments:
  # Disqus comments
  disqus_shortname: 

# Google Analytics Tracking ID
google_analytics: UA-9753249-18

# Social Media Platforms
social_platforms:
  - url: https://www.twitter.com/PBDesk
    fa_icon: fa-twitter
  - url: https://www.facebook.com/Go.PBDesk/
    fa_icon: fa-facebook
  - url: https://www.linkedin.com/in/pinalbhatt
    fa_icon: fa-linkedin
  - url: https://github.com/pinalbhatt/
    fa_icon: fa-github
  - url: https://plus.google.com/
    fa_icon: fa-google-plus
  - url: /#
    fa_icon: fa-rss

# Footer about
footer_about: "Learning endeavor forever… from the desk of Pinal Bhatt <br/><br/> <a href='http://www.pbdesk.com'>PBDesk.com - Pinal Bhatt&quot;s Blog</a> © 2017. All Rights Reserved"
