# Logo
logo_image_source: http://www.pbdesk.com/content/images/2017/03/PBDesk2017Logo.png

# Index Page
index_banner_text: Pinal Bhatt's Blog
index_banner_text_secondary: Learning Endeavour forerver....
index_font_awesome_icon_css: fa fa-magic

# Header
menu:
  Posts: /archives
  Categories: /categories
  Tags: /tags


# Post
default_post_title: Untitled
default_post_icon: fa-file-text-o

# Archive Date Format
archive_date_format: MMM-YYYY
archive_font_awesome_icon_css: fa-folder-open

# About Widget
about_widget_avatar_url: http://tachyons.io/img/avatar_1.jpg
about_widget_text: "My name is Jonathan Klughertz and this is my blog.<br>I am a full stack software engineer with a strong front-end focus.<br> I currently live and work in Singapore, hit me up if you are in the region."


# Comments.
comments:
  # Disqus comments
  disqus_shortname: 

# Google Analytics Tracking ID
google_analytics: UA-9753249-18

# Social Media Platforms
social_platforms:
  - url: https://www.twitter.com/PBDesk
    fa_icon: fa-twitter
  - url: https://www.facebook.com/Go.PBDesk/
    fa_icon: fa-facebook
  - url: https://www.linkedin.com/in/pinalbhatt
    fa_icon: fa-linkedin
  - url: https://github.com/pinalbhatt/
    fa_icon: fa-github
  - url: https://plus.google.com/
    fa_icon: fa-google-plus
  - url: /#
    fa_icon: fa-rss

# Footer about
footer_about: "Learning endeavor forever… from the desk of Pinal Bhatt <br/><br/> <a href='http://www.pbdesk.com'>PBDesk.com - Pinal Bhatt&quot;s Blog</a> © 2017. All Rights Reserved"
